#include "embed.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "util.h"

static bool embArchiveFresh(const EmbeddedEntry *e) {
  struct stat ast;
  if (stat(e->archivePath, &ast) != 0) return false;

  /* Scan freshness: file terbaru di bawah e->src (semua file, atau hanya
     e->pattern jika diset) */
  List files = {0};
  if (e->pattern[0])
    walkDir(e->src, e->pattern, &files);
  else
    walkDir(e->src, "", &files);
  time_t newest = 0;
  for (int i = 0; i < files.count; i++) {
    struct stat st;
    if (stat(files.items[i], &st) == 0 && st.st_mtime > newest) newest = st.st_mtime;
  }
  return newest <= ast.st_mtime;
}

bool emitEmbeddedHeader(const Config *c, bool *changed) {
  char body[8192];
  size_t used = 0;

  used += (size_t)snprintf(
      body + used, sizeof(body) - used,
      "/* Auto-generated by rbot from Buildfile: embedded. Do not edit. */\n"
      "#ifndef RUPA_EMBEDDED_H\n#define RUPA_EMBEDDED_H\n\n");

  for (int i = 0; i < c->embCount; i++) {
    const EmbeddedEntry *e = &c->emb[i];
    if (!e->enable) continue;

    const char *slash = strrchr(e->archivePath, '/');
    const char *archiveFileName = slash ? slash + 1 : e->archivePath;

    /* prefix macro dari nama entri, di-uppercase */
    char prefix[EMBED_NAME_LEN + 8] = {0};
    size_t k = 0;
    for (const char *p = e->name; *p && k < sizeof(prefix) - 1; p++, k++) {
      char ch = *p;
      if (ch >= 'a' && ch <= 'z') ch = (char)(ch - 'a' + 'A');
      bool alnum = (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
                   (ch >= '0' && ch <= '9');
      prefix[k] = alnum ? ch : '_';
    }

    /* nama simbol: karakter non-alnum di path arsip jadi '_' */
    char sym[512] = {0};
    k = 0;
    for (const char *p = e->archivePath; *p && k < sizeof(sym) - 1; p++, k++) {
      char ch = *p;
      bool alnum =
          (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9');
      sym[k] = alnum ? ch : '_';
    }

    used += (size_t)snprintf(
        body + used, sizeof(body) - used,
        "/* ===== embedded entry: %s ===== */\n"
        "#define EMBED_%s_ARCHIVE_NAME \"%s\"\n"
        "#define EMBED_%s_EXTRACT_DIR \"%s\"\n"
        "#define EMBED_%s_SYMBOL _binary_%s_start\n"
        "#define EMBED_%s_SYMBOL_END _binary_%s_end\n\n",
        e->name, prefix, archiveFileName, prefix, e->extract, prefix, sym, prefix, sym);
  }

  used += (size_t)snprintf(body + used, sizeof(body) - used,
                           "#endif /* RUPA_EMBEDDED_H */\n");

  char embeddedHeader[MAX_PATH + 32];
  snprintf(embeddedHeader, sizeof(embeddedHeader), "%s/embedded.h", c->outBuildDir);
  mkparent(embeddedHeader);

  /* lewati penulisan ulang bila tidak berubah agar mtime tetap stabil */
  FILE *rf = fopen(embeddedHeader, "rb");
  if (rf) {
    char existing[8192] = {0};
    size_t n = fread(existing, 1, sizeof(existing) - 1, rf);
    fclose(rf);
    if (n == used && memcmp(existing, body, n) == 0) return true;
  }

  FILE *hf = fopen(embeddedHeader, "w");
  if (!hf) {
    fprintf(stderr, "rbot: cannot write %s\n", embeddedHeader);
    return false;
  }
  fwrite(body, 1, used, hf);
  fclose(hf);
  if (changed) *changed = true;
  return true;
}

static bool buildEmbeddedEntry(const EmbeddedEntry *e) {
  struct stat st;
  if (stat(e->src, &st) != 0 || !S_ISDIR(st.st_mode)) {
    printf("> Embedded  : %s: src '%s' not found, skipped\n", e->name, e->src);
    return true;
  }

  if (!embArchiveFresh(e)) {
    mkparent(e->archivePath);
    bool ok;
    if (e->tar) {
      /* tar dengan gzip opsional (-z) saat with.ext = gz */
      const char *z = (strcmp(e->ext, "gz") == 0) ? "z" : "";
      char *cmd = malloc(strlen(e->archivePath) + strlen(e->src) + 64);
      sprintf(cmd, "tar c%sf %s -C %s .", z, e->archivePath, e->src);
      ok = runCmd(cmd);
      free(cmd);
    } else {
      /* tanpa tar: zip langsung pohon direktorinya (with.ext = gz) */
      char *cmd = malloc(strlen(e->archivePath) + strlen(e->src) + 64);
      sprintf(cmd, "tar czf %s -C %s .", e->archivePath, e->src);
      ok = runCmd(cmd);
      free(cmd);
    }
    if (!ok) {
      fprintf(stderr, "rbot: %s: failed to archive %s\n", e->name, e->src);
      return false;
    }
  }

  if (!newerThan(e->archivePath, e->objectPath)) return true; /* object sudah up-to-date */

  if (system("command -v ld >/dev/null 2>&1") != 0) {
    fprintf(stderr, "rbot: ld not found, embedding skipped\n");
    return true;
  }
  char *cmd = malloc(strlen(e->archivePath) + strlen(e->objectPath) + 64);
  sprintf(cmd, "ld -r -b binary -o %s %s", e->objectPath, e->archivePath);
  bool ok = runCmd(cmd);
  free(cmd);
  if (!ok) fprintf(stderr, "rbot: %s: failed to embed %s\n", e->name, e->archivePath);
  return ok;
}

bool buildEmbedded(const Config *c) {
  for (int i = 0; i < c->embCount; i++) {
    if (!c->emb[i].enable) continue;
    if (!buildEmbeddedEntry(&c->emb[i])) return false;
  }
  return true;
}
